### PR TITLE
feat: A method to get all enrolled biometric types

### PR DESCRIPTION
**Pull request by FreakyAli**

### CODE REVIEW

**Comment by robertmaxted** [comment]
@FreakyAli looks good to me. Have you tested it before you release mate? Just to be sure..

**Review by robertmaxted — APPROVED** [review]

**Comment by FreakyAli** [comment]
@robertmaxted  Yes I tested Android, need to test iOS

**Comment by robertmaxted** [comment]
@FreakyAli brill, all working as expected? Ie provides fingerprint or face id as planned? Thanks again mate.

**Comment by FreakyAli** [comment]
@robertmaxted so I tested it a bit further, it seems that, it responds with whatever is enrolled that it finds first, on Android, so even if Face is enrolled it will respond with Fingerprint, if Fingerprint is enrolled!

**Comment by robertmaxted** [comment]
@FreakyAli Ahh damn.. ok.. I guess if fingerprint is enrolled (ie user has fingerprint biometric saved on device) it isn't an issue? Not ideal but at least it will only try if it has at least one enrolled..?

**Comment by robertmaxted** [comment]
@FreakyAli  message me on discord, it will be much easier to discuss on there.. dazzling_fawn_39070

**Comment by FreakyAli** [comment]
@robertmaxted I have been off Discord for a while but I will see if I can reinstall it, also I was thinking we should maybe make this respond as an array of available options and show everything that is enrolled, it would be easier for sure but it's not like you can choose which authentication would be challenged to the user, it seems the os always decides it on Android

**Comment by robertmaxted** [comment]
@FreakyAli What's the sitch, are you going ahead with the merge? I was thinking about this. If both fingerprint and Face ID are enrolled on Android, the OS will chose the same kind every time (fingerprint) as it has stronger security. Therefore "we" can adjust our UI's accordingly (ie if fingerprint, inform user that fingerprint required etc).. I don't see an issue with that. However it is your repo so your call mate :).

**Comment by FreakyAli** [comment]
@robertmaxted I am gonna turn this into an array, and respond with whatever is available that makes more sense in the long-run if Google decides to fix their issue, on iOS it's always gonna face-id anyway...

**Comment by robertmaxted** [comment]
@FreakyAli Yeah that makes sense (well, for future reasons anyway haha). Cheers mate

**Comment by robertmaxted** [comment]
@FreakyAli Hi mate, any news of when this will be merged? Maybe go ahead with current implementation for now and incorporate the array in the future?

**Comment by FreakyAli** [comment]
@robertmaxted Won't be able to tell you for now, busy for this week, if i get a chance over the weekend i will try

**Comment by robertmaxted** [comment]
@FreakyAli Ok mate, many thanks.

**Pull request merged**
